services:
  postgres:
    container_name: earthquake_postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - earthquake-network

  airflow:
    container_name: earthquake_airflow
    image: apache/airflow:3.0.0
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PYTHONPATH: /opt/airflow/etl
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 1001
    depends_on:
      - postgres
    networks:
      - earthquake-network
    command: >
      bash -c "airflow standalone"

networks:
  earthquake-network:
    driver: bridge
